---
- name: Deploy echoline container
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile
      copy:
        src: ../ansible/roles/echoline/templates/Dockerfile.j2
        dest: /tmp/Dockerfile

    - name: Build echoline container
      shell: docker build -t echoline /tmp
      changed_when: false # этот шаг всегда будет помечен как changed, поэтому отключаем эту метку

    - name: Run echoline container
      docker_container:
        name: echoline
        image: echoline
        state: started
        restart_policy: always
      vars:
        timer_seconds: "{{ echoline_timer_seconds }}" 
        message: "{{ echoline_message }}"