Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/22.04"
    config.vm.provider "virtualbox"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy_echoline.yml"
    end
  end