Vagrant.configure("2") do |config| # vagrant.configure("2") это версия конфигурации, do |config| это блок конфигурации
    config.vm.box = "ubuntu/22.04"
    config.vm.provider "virtualbox"
    config.vm.provision "ansible" do |ansible| # ansible это провиженер, do |ansible| это блок провиженера - конфигурация провиженера
      ansible.playbook = "../ansible/echoline.yaml" # путь к файлу с playbook
    end
  end