---
- name: Build and run echoline container
  docker_container:
    name: echoline
    image: echoline
    state: started
    restart_policy: always
    env:
      TIMER_SECONDS: "{{ timer_seconds }}"
      MESSAGE: "{{ message }}"