- name: Deploy echoline container
  hosts: all
  become: true

  pre_tasks:
    # - name: Install Docker # данная задача не отработала на vagrant, т.е нет реп для docker
    #   apt:
    #     name: docker.io
    #     state: present

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      args:
        warn: no
      changed_when: false
      
    - name: Copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: /tmp/Dockerfile
    
    - name: Copy Dockerfile
      copy:
        src: ../echoline.sh
        dest: /tmp/echoline.sh

    - name: Build echoline container
      shell: docker build -t echoline /tmp
      changed_when: false # этот шаг всегда будет помечен как changed, поэтому отключаем эту метку

  roles:
    - echoline