- name: Deploy echoline container
  hosts: all
  become: true

  pre_tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: /tmp/Dockerfile
    
    - name: Copy Dockerfile
      copy:
        src: ../echoline.sh
        dest: /tmp/echoline.sh

    - name: Build echoline container
      shell: docker build -t echoline /tmp
      changed_when: false # этот шаг всегда будет помечен как changed, поэтому отключаем эту метку

  roles:
    - echoline